
```{r, include=FALSE}
library(gior)
library(dplyr)
library(htmltools)

data("country_data")

globe <- country_data %>%
  gior() %>%
  g_data(from, to, value) %>% 
  g_style("gorgeousDream")
```

```{r, echo=FALSE}
h1(code("gior"), class = "text-center")

div(
  class = "row",
  div(
    class = "col-md-4",
    p(
      "An htmlwidget for",
      tags$a(
        "gio.js",
        href = "http://giojs.org/",
        target = "_blank"
      )
    ),
    tags$a(
      "Shiny demo",
      class = "btn btn-default",
      href = "https://shiny.john-coene.com/gior-shiny/"
    )
  ),
  div(
    class = "col-md-8",
    globe
  )
)
```

> A Declarative 3D Globe Data Visualization Library built with Three.js

## Installation

You can install `gior` with `devtools`

```r
devtools::install_github("JohnCoene/gior")
```

or `remotes`

```r
remotes::install_github("JohnCoene/gior")
```

## Example

```{r, echo=TRUE}
data("country_data")

country_data %>%
  gior() %>%
  g_data(from, to, value)
```

### Notes

`gior` supports continents:

- Oceania
- North America
- South America
- Europe
- Asia
- Africa
